- configs/conferences/32c3/main.less
Fix menu on mobile, more font usage.
> Small fixes for 32c3

- .editorconfig
- template/assemblies/schedule.phtml
- template/overview.phtml
Things I noticed ad 34c3 but had no proper fix – hacking it on gpn18 now.
@MaZderMind please review
> Sched link and overview wide fixes

- README.md
- configs/conferences/lac2018/config.php
- configs/conferences/lac2018/download.sh
- configs/conferences/lac2018/lac-tux.svg
- configs/conferences/lac2018/main.less
(pretty much a copy of minilac2016).
Please review... only 'gefaehrliches Halbwissen'...
> configs/conferences/lac2018/*: Adding lac2018 settings

- configs/conferences/36c3/config.php
> Align hashtag announcement with wiki

- configs/conferences/grr2020/config.php
> [grr] start 15 minutes before

- configs/conferences/archconf2020/config.php
- configs/conferences/archconf2020/main.less
configs/conferences/archconf2020/*:
Add simple configuration and stylesheet for Arch Conf 2020.
> Add configuration for Arch Conf 2020

- configs/conferences/rc3/config.php
changed display name
changed room_guid
changed irc to false
changed twitter hashtag
> added config for chaostrawler channel

- configs/conferences/rc3/config.php
we're streaming to cwtv2 as a stream key, so I've updated that.
> use correct stream name for cwtv

- configs/conferences/rc3/config.php
- configs/conferences/rc3/create_config.php
We haven't been supporting plain IRC sessions for a while and this breaks the connection setup.
> rc3: use ircs protocol handler in webirc links

- configs/conferences/fff/config.php
- configs/conferences/fffpk/config.php
as discussed via mail, here are the config changes needed for the Fridays for Future Germany stream on March 19
> changes for global climate strike of fff

- configs/conferences/cadus-debate/config.php
added CADUS Debate episode #21
> added CADUS Debate Episode 21: Frontex

- configs/conferences/divoc/config.php
- configs/conferences/divoc/main.less
- configs/conferences/divoc/winkebunny.svg
Da kommen evtl. noch Patches vom CSS durch @CodeFreezr, aber hiermit gibt es zumindest keinen "500 Internal Server Error" mehr.
> Fix DiVOC BB3 config

- configs/conferences/revision/config.php
- configs/conferences/revision/main.less
Thanks for the work you already did, just some small tweaks!
One note about the start time: Our stream starts a bit before 16:00 German time, which is why I put in 15:00 as start time. If the server is on a different time zone, this needs to be adjusted!
> Revision 2022 updates

- configs/conferences/aalen-geekend/config.php
Seite für das Geekend in Aalen, wie bereits besprochen.
> Added Config for geekend-aalen

- configs/conferences/jev22/config.json
The GUID is the one of the room in the schedule.json, right?
> JEV22: Add CCL

- configs/conferences/jev22/config.json
> add hackwerk room for jev22

- configs/conferences/jev22/config.json
This commit adds the chat links for [Winterchaos](https://laborluxeria.github.io/winterchaos2022)
> config(jev22): Add Winterchaos chat

- model/Conference.php
- template/assemblies/header.phtml
I didn't find anything else that points to the fullscreen schedule.
Now, it's discoverable without having to ask on the IRC or look at the source code :)
> feat: Add schedule button to header

- configs/conferences/fsck/config.php
> fsck-2023: inital config

- configs/conferences/ds2023/config.php
datenspuren 2023 streaming config
> add datenspuren config

- configs/conferences/why2025meeting/config.json
> Create WHY2025 meeting config file

- configs/conferences/kamphack2024/config.php
Konfiguration für [Kamphack 2024](https://kamphack.de). Stream Key ist gerade noch unbekannt, Mail dazu ist schon raus.
> kamphack2024: add config

- configs/conferences/swisspythonsummit2024/config.php
Configure Swiss Python Summit 2024 event
> config(sps24): Configure Swiss Python Summit 2024 event

- configs/conferences/mrmcd/main.less
this pr fixes a small contrast issue on the front page and integrates room highlighting with the events color scheme
> mrmcd: fix contrast, update schedule coloring

- configs/conferences/dhcp24/config.php
configuration for DHCP24, https://dhcp.cfhn.it
> dhcp24 config

- configs/conferences/cosin2025/config.php
> config(cosin2025): Configure CoSin 2025 event

- configs/conferences/osc25/config.php
> add config for osc25
